# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
      - name: Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa_adlijn
          sudo chmod 600 ~/.ssh/id_rsa_adlijn
          echo "$SSH_CONFIG" > ~/.ssh/config
          curl -LO https://deployer.org/deployer.phar
          chmod +x deployer.phar
          ./deployer.phar deploy -v
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_CONFIG: ${{secrets.SSH_CONFIG}}
